### ISSUE TITLE
Upgrade to v2.0 of the facebook API

### ISSUE THREAD

**Issue by itgoeslikethis** [campaignmonitor/cmfbsub#29]
And do whatever we need to do as a result of this announcement:
https://developers.facebook.com/docs/apps/upgrading

**Comment by jdennes** [comment]
This is the full alert from the developer site:

Platform v1.0 Deprecation
Your app, Campaign Monitor Subscribe Form, is making calls to v1.0 of the Graph API which will be deprecated on Thursday, 30 April 2015. Please upgrade your app to v2.0 or later by that date. The following API requests from your app may be affected.

DEPRECATIONS
The 'username' field on the user object has been removed.
Please read the full changelog here and ensure your app is fully migrated.
23 hours ago

**Comment by jdennes** [comment]
After some quick research, it seems like we should switch from the mogli gem (which now seems completely unmaintained) to: https://github.com/arsduo/koala
